export const SUCCESS = "SUCCESS";
export const ERROR = "ERROR";
export const ERROR_CONNECTION = "ERROR_CONNECTION";

export const CREATE_TASK_START = "CREATE_TASK_START";
export const GET_ALL_TASKS_START = "GET_ALL_TASKS_START";
export const GET_TASK_START = "GET_TASK_START";
export const TOGGLE_TASK_START = "TOGGLE_TASK_START";
export const CLEAN_ALL_TASKS_START = "CLEAN_ALL_TASKS_START";
